import type { ArrayMethodCategory, ArrayMethodDefinition } from '../types';

export const ARRAY_METHOD_CATEGORIES: Record<ArrayMethodCategory, { label: string; description: string }> = {
  mutator: {
    label: 'Mutator',
    description: 'Changes the original array in place.',
  },
  accessor: {
    label: 'Accessor',
    description: 'Returns a new value or array without changing the original.',
  },
  iteration: {
    label: 'Iteration',
    description: 'Loops over elements — often with callbacks.',
  },
  search: {
    label: 'Search & test',
    description: 'Find elements or test conditions.',
  },
  static: {
    label: 'Static',
    description: 'Called on Array itself, not an instance.',
  },
};

export const ARRAY_METHODS: ArrayMethodDefinition[] = [
  {
    id: 'push',
    name: 'push',
    category: 'mutator',
    signature: 'arr.push(...items)',
    description: 'Adds one or more elements to the end and returns the new length.',
    mutates: true,
    returns: 'number',
    example: 'const len = arr.push(4); // [1,2,3,4]',
    defaultArray: '[1, 2, 3]',
    extraArgsLabel: 'Value(s) to add (JSON)',
    defaultExtraArgs: '4',
    extraArgsPlaceholder: '4 or [4, 5]',
  },
  {
    id: 'pop',
    name: 'pop',
    category: 'mutator',
    signature: 'arr.pop()',
    description: 'Removes and returns the last element. Returns undefined if empty.',
    mutates: true,
    returns: 'any | undefined',
    example: 'const last = arr.pop();',
    defaultArray: '[1, 2, 3]',
  },
  {
    id: 'shift',
    name: 'shift',
    category: 'mutator',
    signature: 'arr.shift()',
    description: 'Removes and returns the first element. Shifts remaining indices down.',
    mutates: true,
    returns: 'any | undefined',
    example: 'const first = arr.shift();',
    defaultArray: '[1, 2, 3]',
  },
  {
    id: 'unshift',
    name: 'unshift',
    category: 'mutator',
    signature: 'arr.unshift(...items)',
    description: 'Adds elements to the start and returns the new length.',
    mutates: true,
    returns: 'number',
    example: 'const len = arr.unshift(0);',
    defaultArray: '[1, 2, 3]',
    extraArgsLabel: 'Value(s) to add (JSON)',
    defaultExtraArgs: '0',
  },
  {
    id: 'splice',
    name: 'splice',
    category: 'mutator',
    signature: 'arr.splice(start, deleteCount?, ...items)',
    description: 'Adds/removes elements at an index. Returns removed items as an array.',
    mutates: true,
    returns: 'any[]',
    example: 'arr.splice(1, 1, 99); // remove index 1, insert 99',
    defaultArray: '[1, 2, 3, 4]',
    extraArgsLabel: 'Arguments (JSON array)',
    defaultExtraArgs: '[1, 1, 99]',
    extraArgsPlaceholder: '[start, deleteCount, ...items]',
  },
  {
    id: 'reverse',
    name: 'reverse',
    category: 'mutator',
    signature: 'arr.reverse()',
    description: 'Reverses the array in place and returns the same array reference.',
    mutates: true,
    returns: 'any[]',
    example: 'arr.reverse();',
    defaultArray: '[1, 2, 3]',
  },
  {
    id: 'sort',
    name: 'sort',
    category: 'mutator',
    signature: 'arr.sort(compareFn?)',
    description: 'Sorts in place. Default converts elements to strings and compares UTF-16.',
    mutates: true,
    returns: 'any[]',
    example: 'arr.sort((a, b) => a - b);',
    defaultArray: '[3, 1, 4, 2]',
    extraArgsLabel: 'Compare function (optional)',
    defaultExtraArgs: '(a, b) => a - b',
    extraArgsPlaceholder: '(a, b) => a - b',
  },
  {
    id: 'fill',
    name: 'fill',
    category: 'mutator',
    signature: 'arr.fill(value, start?, end?)',
    description: 'Fills elements from start to end (exclusive) with a static value.',
    mutates: true,
    returns: 'any[]',
    example: 'arr.fill(0, 1, 3);',
    defaultArray: '[1, 2, 3, 4, 5]',
    extraArgsLabel: 'Arguments (JSON array)',
    defaultExtraArgs: '[0, 1, 3]',
  },
  {
    id: 'concat',
    name: 'concat',
    category: 'accessor',
    signature: 'arr.concat(...items)',
    description: 'Merges arrays and/or values into a new array without mutating the original.',
    mutates: false,
    returns: 'any[]',
    example: 'const merged = arr.concat([4, 5]);',
    defaultArray: '[1, 2, 3]',
    extraArgsLabel: 'Value(s) to concat (JSON)',
    defaultExtraArgs: '[4, 5]',
  },
  {
    id: 'slice',
    name: 'slice',
    category: 'accessor',
    signature: 'arr.slice(start?, end?)',
    description: 'Returns a shallow copy of a portion. End index is exclusive.',
    mutates: false,
    returns: 'any[]',
    example: 'const part = arr.slice(1, 3);',
    defaultArray: '[1, 2, 3, 4, 5]',
    extraArgsLabel: 'start, end (JSON array)',
    defaultExtraArgs: '[1, 3]',
  },
  {
    id: 'join',
    name: 'join',
    category: 'accessor',
    signature: 'arr.join(separator?)',
    description: 'Joins all elements into a string, separated by the given separator (default comma).',
    mutates: false,
    returns: 'string',
    example: "arr.join(' - ');",
    defaultArray: '["a", "b", "c"]',
    extraArgsLabel: 'Separator (JSON string)',
    defaultExtraArgs: '" - "',
  },
  {
    id: 'at',
    name: 'at',
    category: 'accessor',
    signature: 'arr.at(index)',
    description: 'Returns the element at index, supporting negative indices from the end.',
    mutates: false,
    returns: 'any | undefined',
    example: 'arr.at(-1); // last element',
    defaultArray: '[10, 20, 30]',
    extraArgsLabel: 'Index (JSON number)',
    defaultExtraArgs: '-1',
  },
  {
    id: 'flat',
    name: 'flat',
    category: 'accessor',
    signature: 'arr.flat(depth?)',
    description: 'Creates a new array with sub-arrays concatenated up to the given depth.',
    mutates: false,
    returns: 'any[]',
    example: 'arr.flat(2);',
    defaultArray: '[1, [2, [3, 4]]]',
    extraArgsLabel: 'Depth (JSON number)',
    defaultExtraArgs: '2',
  },
  {
    id: 'flatMap',
    name: 'flatMap',
    category: 'iteration',
    signature: 'arr.flatMap(callback)',
    description: 'Maps then flattens one level — equivalent to map().flat(1).',
    mutates: false,
    returns: 'any[]',
    example: 'arr.flatMap(x => [x, x * 2]);',
    defaultArray: '[1, 2, 3]',
    extraArgsLabel: 'Callback',
    defaultExtraArgs: 'x => [x, x * 2]',
  },
  {
    id: 'forEach',
    name: 'forEach',
    category: 'iteration',
    signature: 'arr.forEach(callback)',
    description: 'Executes a callback for each element. Returns undefined.',
    mutates: false,
    returns: 'undefined',
    example: 'arr.forEach((x, i) => console.log(i, x));',
    defaultArray: '[1, 2, 3]',
    extraArgsLabel: 'Callback',
    defaultExtraArgs: 'x => x * 2',
  },
  {
    id: 'map',
    name: 'map',
    category: 'iteration',
    signature: 'arr.map(callback)',
    description: 'Creates a new array with the return value of the callback for each element.',
    mutates: false,
    returns: 'any[]',
    example: 'const doubled = arr.map(x => x * 2);',
    defaultArray: '[1, 2, 3]',
    extraArgsLabel: 'Callback',
    defaultExtraArgs: 'x => x * 2',
  },
  {
    id: 'filter',
    name: 'filter',
    category: 'iteration',
    signature: 'arr.filter(callback)',
    description: 'Returns a new array with elements that pass the callback test.',
    mutates: false,
    returns: 'any[]',
    example: 'const evens = arr.filter(x => x % 2 === 0);',
    defaultArray: '[1, 2, 3, 4, 5]',
    extraArgsLabel: 'Callback',
    defaultExtraArgs: 'x => x % 2 === 0',
  },
  {
    id: 'reduce',
    name: 'reduce',
    category: 'iteration',
    signature: 'arr.reduce(callback, initialValue?)',
    description: 'Reduces the array to a single value by applying a callback left-to-right.',
    mutates: false,
    returns: 'any',
    example: 'const sum = arr.reduce((acc, x) => acc + x, 0);',
    defaultArray: '[1, 2, 3, 4]',
    extraArgsLabel: 'Callback and optional initial value',
    defaultExtraArgs: '((acc, x) => acc + x, 0)',
    extraArgsPlaceholder: '(acc, x) => acc + x, 0',
  },
  {
    id: 'find',
    name: 'find',
    category: 'search',
    signature: 'arr.find(callback)',
    description: 'Returns the first element that satisfies the callback, or undefined.',
    mutates: false,
    returns: 'any | undefined',
    example: 'arr.find(x => x > 2);',
    defaultArray: '[1, 5, 3, 8]',
    extraArgsLabel: 'Callback',
    defaultExtraArgs: 'x => x > 2',
  },
  {
    id: 'findIndex',
    name: 'findIndex',
    category: 'search',
    signature: 'arr.findIndex(callback)',
    description: 'Returns the index of the first match, or -1 if none.',
    mutates: false,
    returns: 'number',
    example: 'arr.findIndex(x => x > 2);',
    defaultArray: '[1, 5, 3, 8]',
    extraArgsLabel: 'Callback',
    defaultExtraArgs: 'x => x > 2',
  },
  {
    id: 'some',
    name: 'some',
    category: 'search',
    signature: 'arr.some(callback)',
    description: 'Returns true if at least one element passes the callback test.',
    mutates: false,
    returns: 'boolean',
    example: 'arr.some(x => x > 10);',
    defaultArray: '[1, 2, 3]',
    extraArgsLabel: 'Callback',
    defaultExtraArgs: 'x => x > 2',
  },
  {
    id: 'every',
    name: 'every',
    category: 'search',
    signature: 'arr.every(callback)',
    description: 'Returns true if all elements pass the callback test.',
    mutates: false,
    returns: 'boolean',
    example: 'arr.every(x => x > 0);',
    defaultArray: '[1, 2, 3]',
    extraArgsLabel: 'Callback',
    defaultExtraArgs: 'x => x > 0',
  },
  {
    id: 'includes',
    name: 'includes',
    category: 'search',
    signature: 'arr.includes(searchElement, fromIndex?)',
    description: 'Returns true if the array contains the value (uses SameValueZero).',
    mutates: false,
    returns: 'boolean',
    example: 'arr.includes(2);',
    defaultArray: '[1, 2, 3]',
    extraArgsLabel: 'searchElement, fromIndex?',
    defaultExtraArgs: '2',
  },
  {
    id: 'indexOf',
    name: 'indexOf',
    category: 'search',
    signature: 'arr.indexOf(searchElement, fromIndex?)',
    description: 'Returns the first index of the element, or -1 if not found.',
    mutates: false,
    returns: 'number',
    example: 'arr.indexOf(2);',
    defaultArray: '[1, 2, 3, 2]',
    extraArgsLabel: 'searchElement, fromIndex?',
    defaultExtraArgs: '2',
  },
  {
    id: 'isArray',
    name: 'isArray',
    category: 'static',
    signature: 'Array.isArray(value)',
    description: 'Determines whether the passed value is an Array.',
    mutates: false,
    returns: 'boolean',
    example: 'Array.isArray([1, 2]); // true',
    defaultArray: '[1, 2, 3]',
    extraArgsLabel: 'Value to test (JSON)',
    defaultExtraArgs: '[1, 2, 3]',
  },
  {
    id: 'from',
    name: 'from',
    category: 'static',
    signature: 'Array.from(arrayLike, mapFn?)',
    description: 'Creates a new array from an array-like or iterable object.',
    mutates: false,
    returns: 'any[]',
    example: 'Array.from("abc"); // ["a","b","c"]',
    defaultArray: '[]',
    extraArgsLabel: 'arrayLike and optional mapFn',
    defaultExtraArgs: '("abc")',
    extraArgsPlaceholder: '("abc") or ("abc", x => x.toUpperCase())',
  },
];

export const getArrayMethodById = (id: string) => ARRAY_METHODS.find((m) => m.id === id);
