import type { GenericVisualizationConfig } from '../types/genericVisualization';

export const GENERIC_VISUALIZATION_CONFIGS: Record<string, GenericVisualizationConfig> = {
  'do-while': {
    category: 'loops',
    title: 'How a do...while loop works',
    description: 'The body runs first, then the condition decides whether to continue.',
    overview: 'A do...while is post-check looping: one guaranteed run before evaluating the condition.',
    howItWorks: ['Execute body once', 'Evaluate condition after body', 'Repeat only while condition is true'],
    whenToUse: 'Use when at least one iteration must happen, such as retries or user prompts.',
    takeaway: 'do...while always executes at least one time.',
    code: ['let attempts = 0;', 'do {', '  attempts++;', '} while (attempts < 3);'],
    steps: [
      { line: 1, caption: 'Initialize attempts to 0.', consoleOutput: [], state: [{ label: 'attempts', value: '0' }] },
      { line: 2, caption: 'Enter loop body before any condition check.', consoleOutput: [], state: [{ label: 'attempts', value: '0' }] },
      { line: 3, caption: 'Increment attempts.', consoleOutput: ['attempts = 1'], state: [{ label: 'attempts', value: '1' }] },
      { line: 4, caption: 'Condition true, continue looping.', consoleOutput: ['attempts = 1'], state: [{ label: 'condition', value: '1 < 3 -> true' }] },
      { line: 4, caption: 'After third increment, condition becomes false and loop exits.', consoleOutput: ['attempts = 1', 'attempts = 2', 'attempts = 3'], state: [{ label: 'condition', value: '3 < 3 -> false' }] },
    ],
  },
  'for-of-loop': {
    category: 'loops',
    title: 'How a for...of loop works',
    description: 'Iterate values directly from an iterable without a manual index.',
    overview: 'for...of reads each value in order and assigns it to the loop variable.',
    howItWorks: ['Iterator yields next value', 'Loop variable receives that value', 'Body runs until iterable ends'],
    whenToUse: 'Use for readable value-by-value iteration.',
    takeaway: 'for...of is value-first iteration.',
    code: ["const scores = [10, 20, 30];", 'for (const score of scores) {', '  console.log(score);', '}'],
    steps: [
      { line: 1, caption: 'Create iterable array.', consoleOutput: [], state: [{ label: 'scores', value: '[10, 20, 30]' }] },
      { line: 2, caption: 'First value selected.', consoleOutput: [], state: [{ label: 'score', value: '10' }] },
      { line: 3, caption: 'Print first value.', consoleOutput: ['10'], state: [{ label: 'output', value: '10' }] },
      { line: 3, caption: 'Continue with remaining values.', consoleOutput: ['10', '20', '30'], state: [{ label: 'score progression', value: '10 -> 20 -> 30' }] },
    ],
  },
  'for-in-loop': {
    category: 'loops',
    title: 'How a for...in loop works',
    description: 'Iterate enumerable keys of an object.',
    overview: 'for...in walks keys, then values can be read with bracket notation.',
    howItWorks: ['Enumerate key names', 'Read value via obj[key]', 'Repeat for each key'],
    whenToUse: 'Use for object key traversal.',
    takeaway: 'for...in iterates keys, not values.',
    code: ['const user = { name: "Ravi", role: "admin" };', 'for (const key in user) {', '  console.log(key, user[key]);', '}'],
    steps: [
      { line: 1, caption: 'Object created.', consoleOutput: [], state: [{ label: 'user', value: '{ name, role }' }] },
      { line: 2, caption: 'First key selected.', consoleOutput: [], state: [{ label: 'key', value: 'name' }] },
      { line: 3, caption: 'Log key and value.', consoleOutput: ['name Ravi'], state: [{ label: 'lookup', value: 'user["name"] -> Ravi' }] },
      { line: 3, caption: 'Process next key.', consoleOutput: ['name Ravi', 'role admin'], state: [{ label: 'next key', value: 'role' }] },
    ],
  },
  'nested-loops': {
    category: 'loops',
    title: 'How nested loops work',
    description: 'An inner loop runs completely for each outer-loop iteration.',
    overview: 'Nested loops are common for matrix and pairwise operations.',
    howItWorks: ['Advance outer counter', 'Run inner loop from start to finish', 'Repeat until outer loop ends'],
    whenToUse: 'Use for 2D traversal and pair combinations.',
    takeaway: 'Inner loop cost multiplies total work.',
    code: ['for (let row = 0; row < 2; row++) {', '  for (let col = 0; col < 3; col++) {', '    console.log(row, col);', '  }', '}'],
    steps: [
      { line: 1, caption: 'Start outer row 0.', consoleOutput: [], state: [{ label: 'row', value: '0' }] },
      { line: 2, caption: 'Start inner col 0.', consoleOutput: [], state: [{ label: 'col', value: '0' }] },
      { line: 3, caption: 'Log first pair.', consoleOutput: ['0 0'], state: [{ label: 'pair', value: '(0, 0)' }] },
      { line: 3, caption: 'Complete remaining pairs.', consoleOutput: ['0 0', '0 1', '0 2', '1 0', '1 1', '1 2'], state: [{ label: 'total pairs', value: '6' }] },
    ],
  },
  stack: {
    category: 'data-structures',
    title: 'How stack (LIFO) works',
    description: 'Push adds to top; pop removes from top.',
    overview: 'A stack follows Last-In-First-Out ordering.',
    howItWorks: ['push item', 'push next item', 'pop returns latest item first'],
    whenToUse: 'Use for undo/redo, DFS, parsing.',
    takeaway: 'Most recently added item exits first.',
    code: ['const stack = [];', 'stack.push("A");', 'stack.push("B");', 'const top = stack.pop();'],
    steps: [
      { line: 1, caption: 'Empty stack created.', consoleOutput: [], state: [{ label: 'stack', value: '[]' }] },
      { line: 2, caption: 'Push A.', consoleOutput: ['push A'], state: [{ label: 'stack', value: '[A]' }] },
      { line: 3, caption: 'Push B.', consoleOutput: ['push A', 'push B'], state: [{ label: 'stack', value: '[A, B]' }] },
      { line: 4, caption: 'Pop returns B.', consoleOutput: ['push A', 'push B', 'pop -> B'], state: [{ label: 'stack', value: '[A]' }] },
    ],
  },
  queue: {
    category: 'data-structures',
    title: 'How queue (FIFO) works',
    description: 'Enqueue adds to rear; dequeue removes from front.',
    overview: 'A queue processes items in insertion order.',
    howItWorks: ['enqueue first item', 'enqueue second item', 'dequeue oldest item'],
    whenToUse: 'Use for scheduling and buffered processing.',
    takeaway: 'Oldest item exits first.',
    code: ['const queue = [];', 'queue.push("Task1");', 'queue.push("Task2");', 'const next = queue.shift();'],
    steps: [
      { line: 1, caption: 'Empty queue created.', consoleOutput: [], state: [{ label: 'queue', value: '[]' }] },
      { line: 2, caption: 'Enqueue Task1.', consoleOutput: ['enqueue Task1'], state: [{ label: 'queue', value: '[Task1]' }] },
      { line: 3, caption: 'Enqueue Task2.', consoleOutput: ['enqueue Task1', 'enqueue Task2'], state: [{ label: 'queue', value: '[Task1, Task2]' }] },
      { line: 4, caption: 'Dequeue returns Task1.', consoleOutput: ['enqueue Task1', 'enqueue Task2', 'dequeue -> Task1'], state: [{ label: 'queue', value: '[Task2]' }] },
    ],
  },
  'linked-list': {
    category: 'data-structures',
    title: 'How linked list works',
    description: 'Nodes connect through next pointers.',
    overview: 'Linked lists store data as nodes linked by references.',
    howItWorks: ['Create node', 'Attach next node', 'Traverse by following next'],
    whenToUse: 'Use when insert/delete patterns dominate random access.',
    takeaway: 'Traversal is pointer-following, not index-jumping.',
    code: ['const n1 = { value: 10, next: null };', 'const n2 = { value: 20, next: null };', 'n1.next = n2;', 'let curr = n1;'],
    steps: [
      { line: 1, caption: 'Create first node.', consoleOutput: [], state: [{ label: 'head', value: '10 -> null' }] },
      { line: 2, caption: 'Create second node.', consoleOutput: [], state: [{ label: 'new node', value: '20 -> null' }] },
      { line: 3, caption: 'Link n1 to n2.', consoleOutput: ['link 10 -> 20'], state: [{ label: 'chain', value: '10 -> 20 -> null' }] },
      { line: 4, caption: 'Traversal starts at head.', consoleOutput: ['curr = 10', 'curr.next = 20'], state: [{ label: 'cursor', value: 'n1' }] },
    ],
  },
  'hash-map': {
    category: 'data-structures',
    title: 'How hash map works',
    description: 'Key-value storage for fast lookup.',
    overview: 'Hash maps map keys to buckets for near constant-time access.',
    howItWorks: ['Insert key-value', 'Compute key hash', 'Retrieve by same key'],
    whenToUse: 'Use for counting, indexing, and caching.',
    takeaway: 'Keys provide fast direct access to values.',
    code: ['const counts = new Map();', 'counts.set("apple", 2);', 'counts.set("banana", 1);', 'counts.get("apple");'],
    steps: [
      { line: 1, caption: 'Create empty map.', consoleOutput: [], state: [{ label: 'map size', value: '0' }] },
      { line: 2, caption: 'Insert apple count.', consoleOutput: ['set apple -> 2'], state: [{ label: 'entries', value: '{ apple: 2 }' }] },
      { line: 3, caption: 'Insert banana count.', consoleOutput: ['set apple -> 2', 'set banana -> 1'], state: [{ label: 'entries', value: '{ apple: 2, banana: 1 }' }] },
      { line: 4, caption: 'Lookup apple.', consoleOutput: ['get apple -> 2'], state: [{ label: 'result', value: '2' }] },
    ],
  },
  'event-loop': {
    category: 'javascript',
    title: 'How event loop works',
    description: 'Sync stack runs first, then microtasks, then macrotasks.',
    overview: 'JavaScript coordinates call stack and task queues through the event loop.',
    howItWorks: ['Run sync code', 'Flush microtasks', 'Run next macrotask'],
    whenToUse: 'Use to debug async ordering.',
    takeaway: 'Promise microtasks run before setTimeout callbacks.',
    code: ['console.log("A");', 'setTimeout(() => console.log("T"), 0);', 'Promise.resolve().then(() => console.log("P"));', 'console.log("B");'],
    steps: [
      { line: 1, caption: 'Sync print A.', consoleOutput: ['A'], state: [{ label: 'call stack', value: 'running sync' }] },
      { line: 2, caption: 'Timer callback queued as macrotask.', consoleOutput: ['A'], state: [{ label: 'macrotask queue', value: '[T]' }] },
      { line: 3, caption: 'Promise callback queued as microtask.', consoleOutput: ['A'], state: [{ label: 'microtask queue', value: '[P]' }] },
      { line: 4, caption: 'Sync print B.', consoleOutput: ['A', 'B'], state: [{ label: 'sync complete', value: 'yes' }] },
      { line: 4, caption: 'Drain queues: microtask then macrotask.', consoleOutput: ['A', 'B', 'P', 'T'], state: [{ label: 'final order', value: 'A, B, P, T' }] },
    ],
  },
  'call-stack': {
    category: 'javascript',
    title: 'How call stack works',
    description: 'Each function call pushes a frame; returns pop frames.',
    overview: 'The call stack tracks active execution contexts.',
    howItWorks: ['Call a()', 'a() calls b()', 'b() returns and stack unwinds'],
    whenToUse: 'Use for tracing execution flow and recursion errors.',
    takeaway: 'Execution follows stack push/pop order.',
    code: ['function a() { b(); }', 'function b() { return; }', 'a();', '// done'],
    steps: [
      { line: 3, caption: 'Call a().', consoleOutput: ['call a'], state: [{ label: 'stack', value: '[global, a]' }] },
      { line: 1, caption: 'Inside a(), call b().', consoleOutput: ['call a', 'call b'], state: [{ label: 'stack', value: '[global, a, b]' }] },
      { line: 2, caption: 'b() returns.', consoleOutput: ['return b'], state: [{ label: 'stack', value: '[global, a]' }] },
      { line: 4, caption: 'a() returns; execution complete.', consoleOutput: ['return b', 'return a'], state: [{ label: 'stack', value: '[global]' }] },
    ],
  },
  closures: {
    category: 'javascript',
    title: 'How closures work',
    description: 'Inner function keeps access to outer variables.',
    overview: 'Closures preserve lexical scope state across calls.',
    howItWorks: ['Outer creates private variable', 'Inner captures variable', 'Later calls reuse captured state'],
    whenToUse: 'Use for private state and function factories.',
    takeaway: 'Closure = function + remembered environment.',
    code: ['function makeCounter() { let n = 0; return () => ++n; }', 'const next = makeCounter();', 'next();', 'next();'],
    steps: [
      { line: 1, caption: 'Factory defines n and returns closure.', consoleOutput: [], state: [{ label: 'captured n', value: '0' }] },
      { line: 2, caption: 'Create counter instance.', consoleOutput: ['counter created'], state: [{ label: 'closure state', value: 'n = 0' }] },
      { line: 3, caption: 'First call increments n.', consoleOutput: ['next() -> 1'], state: [{ label: 'closure state', value: 'n = 1' }] },
      { line: 4, caption: 'Second call continues from previous state.', consoleOutput: ['next() -> 1', 'next() -> 2'], state: [{ label: 'closure state', value: 'n = 2' }] },
    ],
  },
  'hoisting-tdz': {
    category: 'javascript',
    title: 'How hoisting & TDZ work',
    description: 'var is hoisted as undefined; let/const are in TDZ before declaration.',
    overview: 'Declarations are processed before execution but initialized differently by keyword.',
    howItWorks: ['var read before line gives undefined', 'let/const read before line throws', 'After declaration both are usable'],
    whenToUse: 'Use to avoid early-access bugs.',
    takeaway: 'Hoisted does not mean safely initialized.',
    code: ['console.log(a);', 'var a = 10;', 'console.log(b);', 'let b = 20;'],
    steps: [
      { line: 1, caption: 'var a exists but is undefined.', consoleOutput: ['undefined'], state: [{ label: 'a', value: 'undefined (hoisted var)' }] },
      { line: 2, caption: 'Assign a = 10.', consoleOutput: ['undefined', 'a = 10'], state: [{ label: 'a', value: '10' }] },
      { line: 3, caption: 'b access before declaration throws TDZ error.', consoleOutput: ['ReferenceError: Cannot access b before initialization'], state: [{ label: 'b', value: 'TDZ' }] },
      { line: 4, caption: 'After declaration b is usable.', consoleOutput: ['b = 20'], state: [{ label: 'b', value: '20' }] },
    ],
  },
  'scope-chain': {
    category: 'javascript',
    title: 'How scope chain works',
    description: 'Identifier lookup moves outward through lexical scopes.',
    overview: 'Name resolution starts locally and walks parent scopes.',
    howItWorks: ['Check current scope first', 'If missing, check outer scopes', 'Stop at first match'],
    whenToUse: 'Use to reason about shadowing.',
    takeaway: 'Nearest declaration wins.',
    code: ['const x = "global";', 'function outer() { const x = "outer"; function inner() { console.log(x); } inner(); }', 'outer();', '// logs outer'],
    steps: [
      { line: 1, caption: 'Global x declared.', consoleOutput: [], state: [{ label: 'global x', value: '"global"' }] },
      { line: 2, caption: 'outer has its own x shadowing global.', consoleOutput: [], state: [{ label: 'outer x', value: '"outer"' }] },
      { line: 3, caption: 'inner lookup finds outer x first.', consoleOutput: ['outer'], state: [{ label: 'resolved x', value: 'outer scope' }] },
      { line: 4, caption: 'Execution ends.', consoleOutput: ['outer'], state: [{ label: 'lookup path', value: 'inner -> outer -> global' }] },
    ],
  },
  recursion: {
    category: 'javascript',
    title: 'How recursion works',
    description: 'Function solves a problem by calling itself with smaller input.',
    overview: 'Recursion needs a base case and progress toward it.',
    howItWorks: ['Check base case', 'Call recursively with smaller input', 'Unwind stack with returns'],
    whenToUse: 'Use for trees, divide-and-conquer, and self-similar problems.',
    takeaway: 'Missing base case causes infinite recursion.',
    code: ['function fact(n) { if (n <= 1) return 1; return n * fact(n - 1); }', 'fact(4);', '// expansion: 4 * 3 * 2 * 1', '// result: 24'],
    steps: [
      { line: 2, caption: 'Call fact(4).', consoleOutput: [], state: [{ label: 'stack', value: 'fact(4)' }] },
      { line: 1, caption: 'Recursive calls descend to base case.', consoleOutput: [], state: [{ label: 'stack', value: 'fact(4)->fact(3)->fact(2)->fact(1)' }] },
      { line: 3, caption: 'Unwind begins: fact(1)=1.', consoleOutput: ['return 1', 'return 2', 'return 6'], state: [{ label: 'partial results', value: '1, 2, 6' }] },
      { line: 4, caption: 'Final result returned.', consoleOutput: ['fact(4) = 24'], state: [{ label: 'result', value: '24' }] },
    ],
  },
  'references-vs-values': {
    category: 'javascript',
    title: 'References vs values',
    description: 'Primitives copy values; objects copy references.',
    overview: 'Object assignment points multiple variables to the same memory object.',
    howItWorks: ['Assign object to another variable', 'Mutate through second variable', 'Observe change through first variable'],
    whenToUse: 'Use to avoid accidental shared mutations.',
    takeaway: 'Clone objects when isolation is needed.',
    code: ['const a = { n: 1 };', 'const b = a;', 'b.n = 2;', 'console.log(a.n);'],
    steps: [
      { line: 1, caption: 'Create object and assign to a.', consoleOutput: [], state: [{ label: 'a', value: '{ n: 1 }' }] },
      { line: 2, caption: 'b points to same object.', consoleOutput: [], state: [{ label: 'a === b', value: 'true' }] },
      { line: 3, caption: 'Mutate through b.', consoleOutput: ['b.n = 2'], state: [{ label: 'shared object', value: '{ n: 2 }' }] },
      { line: 4, caption: 'a sees updated value.', consoleOutput: ['2'], state: [{ label: 'a.n', value: '2' }] },
    ],
  },
  'async-await': {
    category: 'javascript',
    title: 'How async/await works',
    description: 'await pauses async function and resumes later when promise resolves.',
    overview: 'async functions return promises while preserving synchronous-style flow.',
    howItWorks: ['Function starts and hits await', 'Execution yields while promise pending', 'Resume after resolution'],
    whenToUse: 'Use for readable sequential async code.',
    takeaway: 'await does not block the thread; it schedules continuation.',
    code: ['async function load() {', '  const data = await Promise.resolve("ok");', '  return data;', '}', 'load().then(console.log);'],
    steps: [
      { line: 1, caption: 'Define async function.', consoleOutput: [], state: [{ label: 'load()', value: 'returns Promise' }] },
      { line: 2, caption: 'await pauses function until promise resolves.', consoleOutput: [], state: [{ label: 'state', value: 'pending' }] },
      { line: 3, caption: 'Function resumes with resolved value.', consoleOutput: ['data = "ok"'], state: [{ label: 'state', value: 'resumed' }] },
      { line: 5, caption: 'Then handler logs final value.', consoleOutput: ['ok'], state: [{ label: 'promise', value: 'fulfilled' }] },
    ],
  },
};
