import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/card';
import { useI18n } from '@/i18n/I18nProvider';
import { Reveal, Stagger, StaggerItem } from '@/components/Animation';

const TermsOfServicePage = () => {
  const { t } = useI18n();

  const sections = [
    {
      title: '1. Acceptance of Terms',
      body: (
        <p>
          Welcome to ReviseStack (the "Website"). By accessing or using our Website, you agree to be bound by these
          Terms of Service ("Terms") and our Privacy Policy. If you do not agree to these Terms, please do not use the
          Website.
        </p>
      ),
    },
    {
      title: '2. Description of Service',
      body: (
        <p>
          ReviseStack is a platform that provides simplified study topics and quick revision content across multiple
          subject streams — including but not limited to computer science and software development. A significant
          portion of the content available on this Website is generated by artificial intelligence (AI).
        </p>
      ),
    },
    {
      title: '3. AI-Generated Content',
      body: (
        <>
          <p>You acknowledge and agree that:</p>
          <ul className="list-disc list-inside space-y-1 pl-4">
            <li>
              The content provided on this Website is generated by AI and is for informational and educational purposes
              only.
            </li>
            <li>
              While we strive for accuracy, the AI-generated content may contain errors, inaccuracies, or omissions.
            </li>
            <li>
              The content is not a substitute for professional advice. You should not rely on the information on this
              Website as an alternative to professional advice from a qualified expert.
            </li>
            <li>
              We make no representations or warranties of any kind, express or implied, about the completeness,
              accuracy, reliability, suitability, or availability of the content.
            </li>
          </ul>
        </>
      ),
    },
    {
      title: '4. Permitted Use',
      body: (
        <p>
          You are granted a limited, non-exclusive, non-transferable license to access and use the Website and its
          content for your personal, non-commercial purposes, subject to these Terms. You agree not to use the Website
          for any unlawful purpose.
        </p>
      ),
    },
    {
      title: '5. Intellectual Property',
      body: (
        <p>
          The Website and its original content (excluding the AI-generated content, but including the layout, design,
          and branding), features, and functionality are and will remain the exclusive property of ReviseStack and its
          licensors.
        </p>
      ),
    },
    {
      title: '6. Disclaimer of Warranties',
      body: (
        <p>
          The Website is provided on an "AS IS" and "AS AVAILABLE" basis. We disclaim all warranties of any kind,
          whether express or implied, including, but not limited to, the implied warranties of merchantability, fitness
          for a particular purpose, and non-infringement.
        </p>
      ),
    },
    {
      title: '7. Limitation of Liability',
      body: (
        <p>
          In no event shall ReviseStack, nor its directors, employees, partners, agents, suppliers, or affiliates, be
          liable for any indirect, incidental, special, consequential, or punitive damages, including without
          limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access
          to or use of or inability to access or use the Website; (ii) any conduct or content of any third party on the
          Website; (iii) any content obtained from the Website, whether based on warranty, contract, tort (including
          negligence) or any other legal theory, whether or not we have been informed of the possibility of such damage.
        </p>
      ),
    },
    {
      title: '8. Changes to Terms',
      body: (
        <p>
          We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide
          notice of any changes by posting the new Terms on this page. Your continued use of the Website after any such
          changes constitutes your acceptance of the new Terms.
        </p>
      ),
    },
    {
      title: '9. Governing Law',
      body: (
        <p>
          These Terms shall be governed and construed in accordance with the laws of [Your Jurisdiction, e.g., State of
          California, USA], without regard to its conflict of law provisions.
        </p>
      ),
    },
    {
      title: '10. Contact Us',
      body: (
        <p>
          If you have any questions about these Terms, please contact us at{' '}
          <a href="mailto:ladi.ravi884781@gmail.com" className="text-blue-500 hover:underline">
            ladi.ravi884781@gmail.com
          </a>
          .
        </p>
      ),
    },
  ];

  return (
    <div className="container mx-auto p-3 sm:p-4 md:p-8 bg-inherit min-h-screen">
      <Card className="max-w-4xl mx-auto bg-inherit border-none shadow-none">
        <CardHeader>
          <Reveal>
            <CardTitle className="text-2xl sm:text-3xl font-bold text-gradient-sheen">{t('terms.title')}</CardTitle>
          </Reveal>
          <Reveal delay={0.06}>
            <p className="text-sm text-muted-foreground">{t('terms.lastUpdated')}: January 3, 2026</p>
          </Reveal>
        </CardHeader>
        <CardContent>
          <Stagger gap={0.05} className="space-y-6">
            {sections.map((section) => (
              <StaggerItem key={section.title}>
                <div className="space-y-2">
                  <h2 className="text-xl sm:text-2xl font-semibold">{section.title}</h2>
                  {section.body}
                </div>
              </StaggerItem>
            ))}
          </Stagger>
        </CardContent>
      </Card>
    </div>
  );
};

export default TermsOfServicePage;
