export { PRESETS, HTML_PRESET, CSS_PRESET, JAVASCRIPT_PRESET, REACT_PRESET, TAILWIND_PRESET } from './presets';
export {
  HTML_SUGGESTIONS,
  CSS_SUGGESTIONS,
  JAVASCRIPT_SUGGESTIONS,
  REACT_SUGGESTIONS,
  TAILWIND_SUGGESTIONS,
} from './autocompleteSuggestions';
